name: Python Hello World

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the main branch

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set Python version (e.g., 3.8, 3.9)

      # Step 3: Run the Python script
      - name: Run hello.py
        run: |
          python hello.py  # This will run the Python script that prints "Hello, World"
