name: manual-job

on:
  push:
    branches:
      - "**"
  workflow_dispatch:


jobs:
  manual-workflow:
    environment: manual_test
    runs-on: Ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Check version
        run: |
          python --version
        